Rewrite build process and include alpine in master

diff --git a/tests/run b/tests/run
--- a/tests/run
+++ b/tests/run
@@ -1,31 +1,34 @@
 #!/bin/bash
 # See: https://github.com/kward/shunit2
 
-if [ $UID != 0 ] && ! groups | grep -qw docker; then
-    echo "Run with sudo/root or add user $USER to group 'docker'"
-    exit 1
-fi
-
-argBuild=${1:-"build"}
+argImage=$1
 argOutput=${2:-"quiet"}
 argCleanup=${3:-"cleanup"}
 testDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-buildDir="$testDir/.."
-imageName="atmoz/sftp_test"
-buildOptions=(--tag "$imageName")
+imageName="$argImage"
 sshKeyPri="/tmp/atmoz_sftp_test_rsa"
 sshKeyPub="/tmp/atmoz_sftp_test_rsa.pub"
 
-if [ "$argOutput" == "quiet" ]; then
-    redirect="/dev/null"
-else
-    redirect="/dev/stdout"
+if [ $UID != 0 ] && ! groups | grep -qw docker; then
+    echo "Run with sudo/root or add user $USER to group 'docker'"
+    exit 1
 fi
 
 if [ ! -f "$testDir/shunit2/shunit2" ]; then
     echo "Could not find shunit2 in $testDir/shunit2."
     echo "Run 'git submodule update --init'"
     exit 2
+fi
+
+if [ -z "$argImage" ]; then
+    echo "Missing image name"
+    exit 3
+fi
+
+if [ "$argOutput" == "quiet" ]; then
+    redirect="/dev/null"
+else
+    redirect="/dev/stdout"
 fi
 
 # clear argument list (or shunit2 will try to use them)
@@ -36,16 +39,6 @@ set --
 ##############################################################################
 
 function oneTimeSetUp() {
-    if [ "$argBuild" == "build" ]; then
-        buildOptions+=("--no-cache" "--pull=true")
-    fi
-
-    # Build image
-    if ! docker build "${buildOptions[@]}" "$buildDir"; then
-        echo "Build failed"
-        exit 1
-    fi
-
     # Generate temporary ssh keys for testing
     if [ ! -f "$sshKeyPri" ]; then
         ssh-keygen -t rsa -f "$sshKeyPri" -N '' > "$redirect" 2>&1
@@ -53,12 +46,6 @@ function oneTimeSetUp() {
 
     # Private key can not be read by others (sshd will complain)
     chmod go-rw "$sshKeyPri"
-}
-
-function oneTimeTearDown() {
-    if [ "$argCleanup" == "cleanup" ]; then
-        docker image rm "$imageName" > "$redirect" 2>&1
-    fi
 }
 
 function setUp() {
